In [110]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [111]:
def entropy(p):
    if p == 0 or p==1:
        return 0
    return -p*np.log2(p) - (1-p)*np.log2(1-p)

In [112]:
# uses index_feature to determine indices of samples one which one goes to left and to right
def split_indices(X,index_features):
    left_indices=[]
    right_indices=[]
    for idx,x in enumerate(X):
         if x[index_features]==1:               #eg: if features=[Ear Shape, Face Shape, Whiskers],index_features=0 means choosing ear shape
             left_indices.append(idx)           # if X=[[1,0,1],[0,1,1]]] , in first iteration x=[1,0,1] and x[0]=1 so the index 1 of X is placed for left side of split
         else:
             right_indices.append(idx)

    return left_indices,right_indices
    

In [113]:
#to measure average uncertainty of the child nodes after a split, weighted by their sizes
def weighted_entropy(X,y,left_indices,right_indices):
    if len(left_indices) == 0:
        H_left=0
    else:
        pleft=sum(y[left_indices])/len(left_indices)
        H_left=entropy(pleft)
    wleft= len(left_indices)/len(X)
    if len(right_indices) == 0:
        H_right=0
    else:
        pright=sum(y[right_indices])/len(right_indices)
        H_right=entropy(pright)
    wright=len(right_indices)/len(X)

    return wleft*H_left+wright*H_right

    

In [114]:
# to measure how much a split makes data cleaner
def information_gain(X,y,left_indices,right_indices):
    p_node=sum(y)/len(y)
    w_entropy=weighted_entropy(X,y,left_indices,right_indices)
    return entropy(p_node)-w_entropy

In [115]:
# to choose the best split among features given 
def best_split(X,y,features):  #features recieved is in a list form like [0,1,2,.....]

    best_gain = -1            # -1 for comparision simplification(info gain can never be negetive) 
    best_feature = None
    best_indices = None
    for feature in features:
        left_indices,right_indices=split_indices(X,feature)

        if len(left_indices) == 0 or len(right_indices) == 0:       #all data goes to one side , no splitting needed
            continue

        info_gain=information_gain(X,y,left_indices,right_indices)
        if info_gain>best_gain:
            best_gain = info_gain
            best_feature = feature
            best_indices= (left_indices,right_indices)

    return best_feature,best_indices,best_gain

In [116]:
#output is a dictonary something like this:  type(node),feature,left/right -> type(leaf),prediction,indices
def build_tree_recursive(X,y,indices,features,depth,max_depth):            #indices are indices of samples in X and y that belong to current node like indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    y_node=y[indices]                                                      #depth is current depth of the node in the tree
    #stopping condition
    if depth==max_depth or len(set(y_node))==1:            # set() takes a list and removes duplicates that means it checks if all samples in this node belong to the same class
        return {
            "type":"leaf",
            "prediction":int(np.round(np.mean(y_node))),
            "indices":indices
        }
    x_node=X[indices]
    y_node=y[indices]
    best_feature,split,info_gain = best_split(x_node,y_node,features)

    if best_feature == None or info_gain==0:              #that means there is no improvement possible(met the deadend)
        return {
            "type":"leaf",
            "prediction":int(np.round(np.mean(y_node))),
            "indices":indices
        }
    left_local,right_local = split
    left_indices=[]
    for idx in left_local:                              #eg: indices=[0,3,4,5,7], left_local=[0,2,4] then left_indices=[0,4,7]
        left_indices.append(indices[idx])
    right_indices=[indices[idx] for idx in right_local] 

    return {
        "type":"node",
        "feature":best_feature,
        "Left":build_tree_recursive(X,y,left_indices,features,depth+1,max_depth),
        "Right":build_tree_recursive(X,y,right_indices,features,depth+1,max_depth)
    }
       

In [117]:
#text based tree visualization
def visualize_tree(tree, depth=0):
    indent="   "*depth

    if tree["type"]=="leaf":
        print(f"{indent}Leaf-> predict {tree['prediction']} , indices={tree['indices']}")
    else:
        print(f"{indent}Splitting on feature {tree["feature"]}")
        print(f"{indent}Left:")
        visualize_tree(tree["Left"],depth+1)
        print(f"{indent}Right:")
        visualize_tree(tree["Right"],depth+1)
    

In [118]:
def predict(tree, x):
    if tree["type"]=="leaf":
        return tree["prediction"]
    if x[tree["feature"]] == 1:
        return predict(tree["Left"], x)
    else:
        return predict(tree["Right"], x)

In [119]:
#our dataset for heart disease
df=pd.read_csv("C:\\Users\\ACER\\Desktop\\Python\\JN\\heart.csv")
print("1st 5 DataFrame samples:")
print(df.head())
df_local=pd.DataFrame()

#converting contionus value into binary
df_local["age>50"]=(df["age"]>50).astype(int)             # 1 if age>50
df_local["bp_high"]=(df["trestbps"] > 130).astype(int)    # 1 if resting bloop pressure > 130
df_local["col_high"]=(df["chol"] > 240).astype(int)       #1 if cholestrol > 240 mg/dl
df_local["hr_low"]=(df["thalach"]<150).astype(int)        # 1 if maximum heart rate < 150
df_local["oldpeak_high"] = (df["oldpeak"]>1).astype(int)    # high ST depression >1 is 1 ,lower is 0

#one-hot-encoding
df_local["cp_0"]=(df["cp"] == 0).astype(int)        #typical angina chest pain
df_local["cp_1"]=(df["cp"] == 1).astype(int)        #atypical angina chest pain
df_local["cp_2"]=(df["cp"] == 2).astype(int)        #non-anginal pain chest pain
df_local["cp_3"]=(df["cp"] == 3).astype(int)        #asymptomatic chest pain(most dangerous)
df_local["slope_up"] = (df["slope"] == 0).astype(int)
df_local["slope_flat"] = (df["slope"] == 1).astype(int)
df_local["slope_down"] = (df["slope"] == 2).astype(int)
df_local["restecg_0"] = (df["restecg"] == 0).astype(int)      #resting electrocardiographic results
df_local["restecg_1"] = (df["restecg"] == 1).astype(int)
df_local["restecg_2"] = (df["restecg"] == 2).astype(int)
df_local["thal_1"] = (df["thal"] == 1).astype(int)          #normal
df_local["thal_2"] = (df["thal"] == 2).astype(int)          #fixed defect
df_local["thal_3"] = (df["thal"] == 3).astype(int)          #reversible defect
df_local["ca_0"] = (df["ca"] == 0).astype(int)              #number of major vessels (0-3) colored by flourosopy
df_local["ca_1"] = (df["ca"] == 1).astype(int)
df_local["ca_2"] = (df["ca"] == 2).astype(int)
df_local["ca_3"] = (df["ca"] == 3).astype(int)

#others: sex(m=1,f=0),fbs(1 if fasting blood sugar>120 mg/dl),exang(1 if exercise induced angina present), target are already in binary
df_local["sex"] = df["sex"]
df_local["fbs"] = df["fbs"]
df_local["exang"] = df["exang"]

X=df_local.values      #coverting pandas dataframe into numpy array
y=df["target"].values  # 1 for heart disease present

print("X:")
print(X)
print("Y:")
print(y)

1st 5 DataFrame samples:
   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0  
X:
[[1 0 0 ... 1 0 0]
 [1 1 0 ... 1 1 1]
 [1 1 0 ... 1 0 1]
 ...
 [0 0 1 ... 1 0 1]
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 1 0 0]]
Y:
[0 0 0 ... 0 1 0]


In [120]:
#train the tree
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=67)

features = list(range(X_train.shape[1]))  # all feature indices 0,1,...,n-1
train_indices=list(range(len(X_train)))
tree = build_tree_recursive(X_train,y_train,train_indices,features,depth=0,max_depth=20)

In [121]:
#visualize tree
visualize_tree(tree,depth=0)

Splitting on feature 5
Left:
   Splitting on feature 18
   Left:
      Splitting on feature 17
      Left:
         Splitting on feature 4
         Left:
            Leaf-> predict 0 , indices=[45, 68, 76, 84, 106, 116, 165, 196, 214, 230, 251, 270, 293, 316, 337, 376, 402, 413, 419, 487, 490, 498, 520, 539, 553, 567, 577, 598, 644, 651, 673, 689, 702, 718, 744, 745, 752, 770, 777, 808, 812]
         Right:
            Splitting on feature 2
            Left:
               Leaf-> predict 0 , indices=[20, 98, 221, 239, 308, 355, 356, 382, 401, 470, 501, 630, 631, 639, 725]
            Right:
               Splitting on feature 0
               Left:
                  Leaf-> predict 1 , indices=[53, 139, 244, 423, 492, 579, 641, 738]
               Right:
                  Splitting on feature 1
                  Left:
                     Leaf-> predict 0 , indices=[39, 119, 149, 158, 496]
                  Right:
                     Splitting on feature 12
                     Left:


In [122]:
y_predicted = []
for i in range(len(X_test)):
    pred = predict(tree,X_test[i])     #runs the recursive tree prediction for the  i-th row of X_test(features of one patient)
    y_predicted.append(pred)

y_pred = np.array(y_predicted)


#accuracy
accuracy = np.mean( y_pred == y_test) * 100
print(f"Accuracy is {accuracy}")
    


Accuracy is 100.0
